/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { User, Category, Equipment, Allocation, Maintenance, ActivityLog } from './types';

export const PRESET_USERS: User[] = [
  {
    id: 'user-001',
    name: 'Amine Bensaid',
    email: 'amine.bensaid@entreprise.ma',
    role: 'ADMINISTRATEUR',
    department: 'Direction Informatique',
    room: 'Bureau 402',
    isActive: true,
    password: 'admin123',
  },
  {
    id: 'user-002',
    name: 'Sarah Lahlou',
    email: 'sarah.lahlou@entreprise.ma',
    role: 'GESTIONNAIRE',
    department: 'Moyens Généraux / Logistique',
    room: 'Bureau 105',
    isActive: true,
    password: 'gest123',
  },
  {
    id: 'user-003',
    name: 'Karim Tazi',
    email: 'karim.tazi@entreprise.ma',
    role: 'TECHNICIEN',
    department: 'Support Technique',
    room: 'Atelier Hardware',
    isActive: true,
    password: 'tech123',
  },
  {
    id: 'user-004',
    name: 'Yassine Alaoui',
    email: 'yassine.alaoui@entreprise.ma',
    role: 'BENEFICIAIRE',
    department: 'Marketing & Digital',
    room: 'Bureau 203',
    isActive: true,
    password: 'user123',
  },
  {
    id: 'user-005',
    name: 'Layla Meziane',
    email: 'layla.meziane@entreprise.ma',
    role: 'BENEFICIAIRE',
    department: 'Finance & Comptabilité',
    room: 'Bureau 310',
    isActive: true,
    password: 'user123',
  },
  {
    id: 'user-006',
    name: 'Omar Rami',
    email: 'omar.rami@entreprise.ma',
    role: 'BENEFICIAIRE',
    department: 'Recherche & Développement',
    room: 'Laboratoire Lab-01',
    isActive: true,
    password: 'user123',
  },
];

export const PRESET_CATEGORIES: Category[] = [
  {
    id: 'cat-001',
    name: 'Ordinateurs',
    code: 'ORD',
    icon: 'Laptop',
    description: 'PC Portables, PC fixes de bureau, et serveurs de calcul',
  },
  {
    id: 'cat-002',
    name: 'Écrans',
    code: 'ECR',
    icon: 'Monitor',
    description: 'Moniteurs, écrans secondaires, et VP / projecteurs de salles de réunion',
  },
  {
    id: 'cat-003',
    name: 'Imprimantes',
    code: 'IMP',
    icon: 'Printer',
    description: 'Imprimantes laser, scanners, photocopieurs multifonctions',
  },
  {
    id: 'cat-004',
    name: 'Équipements Réseau',
    code: 'RES',
    icon: 'Network',
    description: 'Switches, routeurs, bornes d\'accès Wi-Fi et pare-feux physiques',
  },
  {
    id: 'cat-005',
    name: 'Accessoires',
    code: 'ACC',
    icon: 'Keyboard',
    description: 'Claviers, souris, stations d\'accueil, webcams et casques audio',
  },
];

export const PRESET_EQUIPMENTS: Equipment[] = [
  {
    id: 'eq-001',
    codeInventaire: 'INV-ORD-001',
    serialNumber: 'SN-DELL-9988X23',
    categoryId: 'cat-001',
    brand: 'Dell',
    model: 'XPS 15 9520',
    purchaseDate: '2025-01-15',
    purchasePrice: 1850,
    provider: 'Dell Maroc',
    warrantyMonths: 36,
    status: 'Disponible',
    state: 'Excellent',
    location: 'Magasin Principal',
    comment: 'Matériel révisé récemment après retour de maintenance.',
  },
  {
    id: 'eq-002',
    codeInventaire: 'INV-ORD-002',
    serialNumber: 'SN-APPL-C02F23KL',
    categoryId: 'cat-001',
    brand: 'Apple',
    model: 'MacBook Pro 14" M3',
    purchaseDate: '2025-11-10',
    purchasePrice: 2400,
    provider: 'iStyle Maroc',
    warrantyMonths: 24,
    status: 'Affecté',
    state: 'Excellent',
    location: 'Bureau 310',
    comment: 'Fourni avec housse et adaptateur multi-ports.',
  },
  {
    id: 'eq-003',
    codeInventaire: 'INV-ECR-001',
    serialNumber: 'SN-DELL-552319P',
    categoryId: 'cat-002',
    brand: 'Dell',
    model: 'UltraSharp U2723QE 27"',
    purchaseDate: '2025-02-20',
    purchasePrice: 550,
    provider: 'Dell Maroc',
    warrantyMonths: 36,
    status: 'Affecté',
    state: 'Bon',
    location: 'Bureau 203',
    comment: 'Alimentation par USB-C supportée.',
  },
  {
    id: 'eq-004',
    codeInventaire: 'INV-IMP-001',
    serialNumber: 'SN-HPLJ-404DN91',
    categoryId: 'cat-003',
    brand: 'HP',
    model: 'LaserJet Pro M404dn',
    purchaseDate: '2024-06-05',
    purchasePrice: 320,
    provider: 'Electro-Planète',
    warrantyMonths: 12,
    status: 'En maintenance',
    state: 'En panne',
    location: 'Atelier Hardware',
    comment: 'Problème de rouleaux entraîneurs de papier et bruit mécanique persistant.',
  },
  {
    id: 'eq-005',
    codeInventaire: 'INV-RES-001',
    serialNumber: 'SN-CISC-2960X48',
    categoryId: 'cat-004',
    brand: 'Cisco',
    model: 'Catalyst 2960-X 48 Ports',
    purchaseDate: '2024-01-20',
    purchasePrice: 1200,
    provider: 'Cisco Gold Partner',
    warrantyMonths: 60,
    status: 'Disponible',
    state: 'Moyen',
    location: 'Local Réseau Central',
    comment: 'Switch de secours. Quelques ports d\'extrémité présentent du bruit / des pertes.',
  },
  {
    id: 'eq-006',
    codeInventaire: 'INV-ORD-003',
    serialNumber: 'SN-LENO-2023TY5',
    categoryId: 'cat-001',
    brand: 'Lenovo',
    model: 'ThinkCentre M70q Tiny',
    purchaseDate: '2025-03-12',
    purchasePrice: 750,
    provider: 'Techno-Dist',
    warrantyMonths: 36,
    status: 'Affecté',
    state: 'Bon',
    location: 'Salle de TP C204',
    comment: 'Ordinateur compact vissé à l\'arrière du moniteur.',
  },
  {
    id: 'eq-007',
    codeInventaire: 'INV-RES-002',
    serialNumber: 'SN-TPLK-WF2025',
    categoryId: 'cat-004',
    brand: 'TP-Link',
    model: 'Archer AX55 Wi-Fi 6',
    purchaseDate: '2025-10-01',
    purchasePrice: 110,
    provider: 'Virgin Megastore',
    warrantyMonths: 24,
    status: 'Disponible',
    state: 'Excellent',
    location: 'Magasin Principal',
    comment: 'Sous emballage d\'origine.',
  },
  {
    id: 'eq-008',
    codeInventaire: 'INV-ACC-001',
    serialNumber: 'SN-LOGI-H390X',
    categoryId: 'cat-005',
    brand: 'Logitech',
    model: 'USB Headset H390',
    purchaseDate: '2025-11-20',
    purchasePrice: 45,
    provider: 'Techno-Dist',
    warrantyMonths: 12,
    status: 'Disponible',
    state: 'Bon',
    location: 'Magasin Principal',
    comment: 'Remis au stock pour désinfection.',
  },
];

export const PRESET_ALLOCATIONS: Allocation[] = [
  {
    id: 'alloc-001',
    equipmentId: 'eq-002',
    equipmentCode: 'INV-ORD-002',
    equipmentModel: 'MacBook Pro 14" M3 (Apple)',
    beneficiaryId: 'user-005',
    beneficiaryType: 'Utilisateur',
    beneficiaryName: 'Layla Meziane',
    allocatedDate: '2025-11-12',
    responsableName: 'Sarah Lahlou',
    notes: 'Dotation initiale pour les besoins de clôture comptable.',
    status: 'En cours',
  },
  {
    id: 'alloc-002',
    equipmentId: 'eq-003',
    equipmentCode: 'INV-ECR-001',
    equipmentModel: 'UltraSharp U2723QE 27" (Dell)',
    beneficiaryId: 'user-004',
    beneficiaryType: 'Utilisateur',
    beneficiaryName: 'Yassine Alaoui',
    allocatedDate: '2025-02-22',
    responsableName: 'Sarah Lahlou',
    notes: 'Affectation pour le poste de design graphique.',
    status: 'En cours',
  },
  {
    id: 'alloc-003',
    equipmentId: 'eq-006',
    equipmentCode: 'INV-ORD-003',
    equipmentModel: 'ThinkCentre M70q Tiny (Lenovo)',
    beneficiaryId: 'Salle de TP C204',
    beneficiaryType: 'Salle',
    beneficiaryName: 'Salle de TP C204',
    allocatedDate: '2025-03-15',
    responsableName: 'Amine Bensaid',
    notes: 'Poste enseignant pour travaux pratiques.',
    status: 'En cours',
  },
  {
    id: 'alloc-004',
    equipmentId: 'eq-001',
    equipmentCode: 'INV-ORD-001',
    equipmentModel: 'XPS 15 9520 (Dell)',
    beneficiaryId: 'user-006',
    beneficiaryType: 'Utilisateur',
    beneficiaryName: 'Omar Rami',
    allocatedDate: '2025-01-20',
    returnedDate: '2026-05-30',
    responsableName: 'Sarah Lahlou',
    notes: 'Retourné pour diagnostic écran d\'abord, puis remis au stock dispo.',
    status: 'Clôturée',
  },
];

export const PRESET_MAINTENANCES: Maintenance[] = [
  {
    id: 'maint-001',
    equipmentId: 'eq-004',
    equipmentCode: 'INV-IMP-001',
    equipmentModel: 'LaserJet Pro M404dn (HP)',
    reportedDate: '2026-06-05',
    failureDescription: 'Bourrage papier récurrent à la prise de feuille, grondement sourd lors de l\'entraînement mécanique.',
    diagnostics: 'Galets d\'entraînement usés et four de fusion ayant atteint sa limite de cycle thermique.',
    status: 'En cours',
    technicianName: 'Karim Tazi',
  },
  {
    id: 'maint-002',
    equipmentId: 'eq-001',
    equipmentCode: 'INV-ORD-001',
    equipmentModel: 'XPS 15 9520 (Dell)',
    reportedDate: '2026-05-25',
    failureDescription: 'Extinction intermittente de l\'écran lors des mouvements de charnière.',
    diagnostics: 'Connecteur vidéo eDP interne légèrement délogé et poussière accumulée obstruant les ventilateurs.',
    solution: 'Recâblage du connecteur eDP, resserrage de la connectique carte mère, dépoussiérage des ventilateurs et changement de pâte thermique.',
    cost: 45,
    status: 'Clôturée',
    technicianName: 'Karim Tazi',
    endDate: '2026-05-29',
    finalState: 'Excellent',
  },
];

export const PRESET_LOGS: ActivityLog[] = [
  {
    id: 'log-001',
    timestamp: '2025-01-15T09:30:00Z',
    operatorName: 'Amine Bensaid',
    operatorRole: 'ADMINISTRATEUR',
    actionType: 'Création',
    description: 'Enregistrement de l\'ordinateur Dell XPS 15 (INV-ORD-001) dans le stock.',
    equipmentId: 'eq-001',
    equipmentCode: 'INV-ORD-001',
  },
  {
    id: 'log-002',
    timestamp: '2025-01-20T11:00:00Z',
    operatorName: 'Sarah Lahlou',
    operatorRole: 'GESTIONNAIRE',
    actionType: 'Affectation',
    description: 'Affectation de l\'équipement INV-ORD-001 à l\'utilisateur Omar Rami.',
    equipmentId: 'eq-001',
    equipmentCode: 'INV-ORD-001',
  },
  {
    id: 'log-003',
    timestamp: '2025-11-10T14:45:00Z',
    operatorName: 'Amine Bensaid',
    operatorRole: 'ADMINISTRATEUR',
    actionType: 'Création',
    description: 'Enregistrement du MacBook Pro 14" (INV-ORD-002) acquis via iStyle Maroc.',
    equipmentId: 'eq-002',
    equipmentCode: 'INV-ORD-002',
  },
  {
    id: 'log-004',
    timestamp: '2025-11-12T10:15:00Z',
    operatorName: 'Sarah Lahlou',
    operatorRole: 'GESTIONNAIRE',
    actionType: 'Affectation',
    description: 'Affectation de l\'ordinateur INV-ORD-002 à Layla Meziane.',
    equipmentId: 'eq-002',
    equipmentCode: 'INV-ORD-002',
  },
  {
    id: 'log-005',
    timestamp: '2026-05-25T08:30:00Z',
    operatorName: 'Omar Rami',
    operatorRole: 'BENEFICIAIRE',
    actionType: 'Panne',
    description: 'Signalement de panne sur INV-ORD-001 (écran noir par intermittence). Transfert vers atelier.',
    equipmentId: 'eq-001',
    equipmentCode: 'INV-ORD-001',
  },
  {
    id: 'log-006',
    timestamp: '2026-05-30T16:00:00Z',
    operatorName: 'Karim Tazi',
    operatorRole: 'TECHNICIEN',
    actionType: 'Maintenance',
    description: 'Clôture de la maintenance sur INV-ORD-001. Nettoyage et remise au stock "Disponible" en Excellent état.',
    equipmentId: 'eq-001',
    equipmentCode: 'INV-ORD-001',
  },
];
